#!/bin/bash
# test database is running before issuing timzone command
echo "Checking whether database(s) are ready"
until [ "$( mysqladmin -u root status 2>&1 >/dev/null | grep -ci error:)" = "0" ]
do
echo "waiting....."
sleep 2s
done
exec /sbin/setuser abc /opt/kodi-server/lib/kodi/kodi.bin  --nolirc --headless -p
